 name: gitartwork from a contribution graph
 on: 
   push:
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: jasineri/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: lewiii254
            # Text on contribution graph 
            text: MARKLEWIS
       - uses: jasineri/simple-push-action@v1
